version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql/user/:/docker-entrypoint-initdb.d/
      
  mysql-new:
    image: mysql
    container_name: mysql-new
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql/data/:/docker-entrypoint-initdb.d/

  server:
    build: ./server
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=mysql-new
      - MYSQLDB=new_database
      - MYSQLUSER=root
      - MYSQLPASS=example
      - JWTSECRET=supersecretpassword
    volumes:
      - ./server/backend:/app/backend
      - ./server/frontend:/app/frontend
    ports:
      - "8003:80"
    depends_on:
      - mysql-new
  user-management-api:
    build: ./server/user-management-api
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=mysql
      - MYSQLDB=users
      - MYSQLUSER=root
      - MYSQLPASS=example
      - PEPPER=ef79
      - TOTP=SPURGEON_BOURNE
      - JWTSECRET=supersecretpassword
    volumes:
      - ./server/user-management-api/backend:/app/backend
    ports:
      - "8004:80"
    depends_on:
      - mysql
